name: .NET Framework Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore FreeMove.sln

    - name: Build Solution
      run: msbuild FreeMove.sln /p:Configuration=Release



    - name: Find and Package Release
      run: |
        $exePath = Get-ChildItem -Recurse -Filter FreeMove.exe | Where-Object { $_.DirectoryName -like '*\bin\Release*' } | Select-Object -First 1
        if ($null -eq $exePath) {
          echo "FreeMove.exe not found in any Release directory!"
          exit 1
        }
        echo "Found executable at: $($exePath.FullName)"
        mkdir release
        Copy-Item -Path $exePath.FullName -Destination release/
        Compress-Archive -Path release/* -DestinationPath FreeMove-Release.zip
      shell: pwsh

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: FreeMove-Release.zip

